project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: 'https://scholar.google.co.uk/citations?user=BxTPh1kAAAAJ&hl=en'
        text: Publications
      - href: gue.qmd
        text: Global urban ecosystems
    left: 
      - icon: github
        href: https://github.com/drexrichards
      - icon: twitter
        href: https://twitter.com/DanRRichards
      - icon: linkedin
        href: https://www.linkedin.com/in/danrichardsaps/
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

