---
title: "Climate change datasets and methods"
---

This page provides a brief description of the source datasets and methods used for all environmental and climate change datasets included in the GenAI platform.

### Land cover

Land cover was mapped using the Land Cover Database (LCDB) v5, a multi-temporal, thematic classification of New Zealand's land cover. It identifies 33 mainland land cover classes. LCDB v5 is derived from satellite imagery collected in summer 2018/19 and has a minimum area mapping unit of approximately 1 ha. LCDB is a product of Manaaki Whenua - Landcare Research and is available online; [LCDB](https://lris.scinfo.org.nz/layer/104400-lcdb-v50-land-cover-database-version-50-mainland-new-zealand/)

### Pasture production

Pasture production data under [historical](https://landuseopportunities.nz/dataset/pasture-production-maps) and projected [future](https://landuseopportunities.nz/dataset/pasture-production-maps-under-climate-change) climates were obtained from the Our Land and Water Data Supermarket. The pasture production surfaces were derived from biomass accumulation simulated using the Agricultural Production Systems Simulator (APSIM) model. Simulations approximate a continuous ryegrass/white clover mixed pasture under rotational defoliation. For areas mapped as being [under irrigation](https://data.mfe.govt.nz/layer/105407-irrigated-land-area-raw-2020-update/) in 2020, we assumed irrigation was present, while in other areas we assumed no irrigation. The simulations did not account for pests and diseases nor for nutrient limitations (other than nitrogen). Daily weather data was sourced from the NIWA CMPI5 downscaled Climate Change projections. Simulations were run using data from three GCMs (HadGEM2-ES, CESM1-CAM5, and GISS-EL-R) for each RCP (2.6, 4.5, 6.0, and 8.5).

### Population density

These population data are derived from the official [NZ census 2023](https://datafinder.stats.govt.nz/layer/119478-2023-census-population-change-by-statistical-area-2/). This dataset contains census usually resident population counts from the 2013, 2018, and 2023 Censuses, as well as the percentage change in the population count between the 2013 and 2018 Censuses, and between the 2018 and 2023 Censuses. Data is available by statistical area 2. The census usually resident population count of an area (subnational count) is a count of all people who usually live in that area and were present in New Zealand on census night. It excludes visitors from overseas, visitors from elsewhere in New Zealand, and residents temporarily overseas on census night. For example, a person who usually lives in Christchurch city and is visiting Wellington city on census night will be included in the census usually resident population count of Christchurch city.

### NIWA Climate projections

We use the NIWA [national climate projections](https://climatedata.environment.govt.nz/) for Aotearoa New Zealand. This is the CMPI6 climate projections downscaling for New Zealand. This data provides us with information about key climate variables such as temperature, rainfall, wind, and drought and how they might change into the future. These projections were created using six global models, published as part of the Intergovernmental Panel for Climate Change Sixth Assessment Report in 2021, and downscaled to provide New Zealand specific projections at a 5km grid. The data is used here as a multi model mean or "ensemble", meaning it shows the average of the values produced, Range in daily temperature (°C), Number of frost days (\<=0°C), Growing degree days (base 5°C), Potential evaporation deficit (mm), Total annual precipitation (mm), Number of very rainy days (\>25mm), Average solar radiation (W/m2), Average daily temperature (°C), Average daily minimum temperature (°C), Number of hot days (\>25°C).
